[workspace]

members = [
  "filecoin-proofs",
  "storage-proofs-core",
  "storage-proofs-porep",
  "storage-proofs-post",
  "fil-proofs-tooling",
  "fil-proofs-param",
  "fr32",
  "sha2raw",
  "filecoin-hashers",
]

[patch.crates-io]
rust-gpu-tools = { git = "https://github.com/filecoin-project/rust-gpu-tools", branch = "master" }
neptune = { git = "https://github.com/filecoin-project/neptune", branch = "opencl3" }
bellperson = { git = "https://github.com/filecoin-project/bellperson", branch = "opencl3" }
