[workspace]

members = [
  "filecoin-proofs",
  "storage-proofs-core",
  "storage-proofs-porep",
  "storage-proofs-post",
  "fil-proofs-tooling",
  "fil-proofs-param",
  "fr32",
  "sha2raw",
  "filecoin-hashers",
  "storage-proofs-update",
  "fil-halo2-gadgets",
]

[patch.crates-io]
halo2_proofs = { git = "https://github.com/filecoin-project/halo2", branch = "halo2" }
neptune = { git = "https://github.com/filecoin-project/neptune", branch = "halo2-gpu" }
pasta_curves = { git = "https://github.com/filecoin-project/pasta_curves", branch = "gpu" }
fil_pasta_curves = { git = "https://github.com/filecoin-project/pasta_curves", branch = "gpu-fil-fork" }
