[workspace]

members = [
  "filecoin-proofs",
  "storage-proofs",
  "storage-proofs/core",
  "storage-proofs/porep",
  "storage-proofs/post",
  "fil-proofs-tooling",
  "fil-proofs-param",
  "sha2raw",
  "phase2",
  "filecoin-hashers",
]

