[workspace]

members = [
  "filecoin-proofs",
  "storage-proofs-core",
  "storage-proofs-porep",
  "storage-proofs-post",
  "fil-proofs-tooling",
  "fil-proofs-param",
  "fr32",
  "sha2raw",
  "filecoin-hashers",
]

[patch.crates-io]
bellperson = { git = "https://github.com/Zondax/bellperson.git", branch = "scheduler", version = "0.13", default-features = false }
rust-gpu-tools = { version = "0.3.0", git = "https://github.com/Zondax/rust-gpu-tools.git" , branch = "unique_id"}
neptune = { version = "2.2.0", default-features = false, git = "https://github.com/Zondax/neptune.git", branch = "granularity" }
