[workspace]

members = [
  "filecoin-proofs",
  "storage-proofs",
  "fil-proofs-tooling",
]

[patch.crates-io]
bellperson = { path = "../../../opensource/bellperson" }#git = "https://github.com/filecoin-project/bellman", branch = "feat/verify-batch" }