[package]
name = "fr32"
version = "1.0.3"
authors = ["dignifiedquire <me@dignifiedquire.com>"]
description = "Filecoin proofs Fr/32-byte conversion tooling"
license = "MIT OR Apache-2.0"
edition = "2018"
repository = "https://github.com/filecoin-project/rust-fil-proofs"

[dependencies]
anyhow = "1.0.23"
bellperson = { git = "https://github.com/filecoin-project/bellperson", branch = "halo" }
byte-slice-cast = "1.0.0"
byteorder = "1"
ff = "0.10.0"
thiserror = "1.0.6"

[dev-dependencies]
bitvec = "0.17"
criterion = "0.3"
itertools = "0.9"
pretty_assertions = "0.6.1"
rand = "0.8"
rand_xorshift = "0.3"

[features]
default = []
gpu = ["bellperson/gpu"]

[[bench]]
name = "fr"
harness = false
