[package]
name = "storage-proofs"
version = "0.1.0"
authors = ["dignifiedquire <dignifiedquire@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
bitvec = "0.5"
rand = "0.4"
sapling-crypto = { git = "https://github.com/filecoin-project/sapling-crypto", branch = "master" }
libc = "0.2"
merkle_light = { git = "https://github.com/filecoin-project/merkle_light", branch = "master" }
failure = "0.1"
bellman = "0.1"
byteorder = "1"
itertools = "0.7.3"
lazy_static = "1.0"
memmap = "0.6"
num-bigint = "0.2"
num-traits = "0.2"
clap = "2"
log = "0.4"
env_logger = "0.5"
colored = "1.6"
aes = "0.1"
block-modes = "0.1"
sha2 = "0.8"
blake2 = "0.8"
pbr = "1.0"
tempfile = "3"
fs2 = "0.4"
rayon = "1.0.0"

[dependencies.pairing]
version = "0.14.2"
features = ["expose-arith"]

[features]
default = ["u128-support"]
u128-support = ["pairing/u128-support"]
simd = ["blake2/simd_opt"]
asm = ["sha2/sha2-asm", "blake2/simd_asm"]

[dev-dependencies]
proptest = "0.7"
criterion = "0.2"
sector-base = { path = "../sector-base" }

[[bench]]
name = "pedersen"
harness = false

[[bench]]
name = "sha256"
harness = false

[[bench]]
name = "blake2s"
harness = false

[[bench]]
name = "drgraph"
harness = false

[[bench]]
name = "preprocessing"
harness = false

[[bench]]
name = "sloth"
harness = false
