[package]
name = "storage-proofs"
description = "Implementations of Proofs of Storage."
version = "1.0.0-alpha.0"
authors = ["dignifiedquire <dignifiedquire@gmail.com>", "laser <l@s3r.com>", "porcuquine <porcuquine@users.noreply.github.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
repository = "https://github.com/filecoin-project/rust-fil-proofs"
readme = "README.md"

[lib]
bench = false

[dependencies]
bitvec = "0.5"
rand = "0.7"
libc = "0.2"
merkletree = "0.16.4"
byteorder = "1"
config = "0.9.3"
crossbeam-utils = "0.6"
itertools = "0.8"
lazy_static = "1.2"
memmap = "0.7"
num-bigint = "0.2"
num-traits = "0.2"
clap = "2"
colored = "1.6"
aes = "0.3"
block-modes = "0.3"
sha2 = { version = "0.8.0", package = "sha2ni" }
sha2raw = { version = "0.1.0", path = "../sha2raw" }
pbr = "1.0"
tempfile = "3"
tempdir = "0.3.7"
fs2 = "0.4"
rayon = "1.0.0"
serde = { version = "1.0", features = ["derive"]}
base64 = "0.11.0"
blake2b_simd = "0.5"
blake2s_simd = "0.5"
toml = "0.5"
ff = { version = "0.2.1", package = "fff" }
bellperson = "0.6.2"
paired = { version = "0.18.0", features = ["serde"] }
fil-sapling-crypto = "0.4.1"
serde_json = "1.0"
log = "0.4.7"
pretty_assertions = "0.6.1"
crossbeam = "0.7.2"
num_cpus = "1.10.1"
rand_xorshift = "0.2.0"
rand_chacha = "0.2.1"
hex = "0.4.0"
generic-array = "0.13.2"
anyhow = "1.0.23"
thiserror = "1.0.6"
cpu-time = "1.0.0"
neptune = "0.5.1"
once_cell = "1.3.1"

[features]
default = ["gpu"]
simd = []
asm = ["sha2/sha2-asm"]
big-sector-sizes-bench = []
gpu = ["bellperson/gpu", "fil-sapling-crypto/gpu"]
measurements = []
profile = ["measurements"]

[dev-dependencies]
proptest = "0.7"
criterion = "0.3"
femme = "1.2.0"

[[bench]]
name = "pedersen"
harness = false

[[bench]]
name = "sha256"
harness = false

[[bench]]
name = "blake2s"
harness = false

[[bench]]
name = "drgraph"
harness = false

[[bench]]
name = "encode"
harness = false

[[bench]]
name = "parents"
harness = false

[[bench]]
name = "xor"
harness = false

[[bench]]
name = "fr"
harness = false

[[bench]]
name = "merkle"
harness = false

[[bench]]
name = "misc"
harness = false
