[package]
name = "storage-proofs"
version = "0.1.0"
authors = ["dignifiedquire <dignifiedquire@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
bitvec = "0.5"
sapling-crypto = { git = "https://github.com/zcash-hackworks/sapling-crypto", branch = "master" }
rand = "0.4"
libc = "0.2"
merkle_light = { git = "https://github.com/dignifiedquire/merkle_light", branch = "master" }
failure = "0.1"
bellman = "0.1"
byteorder = "1"
itertools = "0.7.3"
lazy_static = "1.0"
memmap = "0.6"
num-bigint = "0.2"
num-traits = "0.2"
clap = "2"
log = "0.4"
env_logger = "0.5"
colored = "1.6"
aes = "0.1"
block-modes = "0.1"
sha2 = "0.7"
pbr = "1.0"
tempfile = "3"
fs2 = "0.4"

[dependencies.pairing]
version = "0.14.2"
features = ["expose-arith"]

[dependencies.blake2-rfc]
git = "https://github.com/gtank/blake2-rfc"
rev = "c7c458429c429b81fea845421f5ab859710fa8af"

[features]
default = ["u128-support"]
u128-support = ["pairing/u128-support"]

[dev-dependencies]
proptest = "0.7"
criterion = "0.2"

[[bench]]
name = "pedersen"
harness = false

[[bench]]
name = "drgraph"
harness = false

[profile.test]
opt-level = 1
