[export]
# A list of symbols to not include in the generated bindings
exclude = ["MerkleTree"]

[parse]
# Whether to parse dependent crates and include their types in the generated
# bindings
parse_deps = true
# A white list of crate names that are allowed to be parsed
include = ["sector_base"]
